[profile.default]
evm_version = "cancun"
ffi = true
fs_permissions = [{access = "read-write", path = ".forge-snapshots/"}]
libs = ["lib"]
out = "out"
solc_version = "0.8.30"
src = "src"
via_ir = false
bytecode_hash = "none"
cbor_metadata = false

[rpc_endpoints] 
arbitrum_sepolia = "https://arb-sepolia.g.alchemy.com/v2/eoDKFwWxqATc20dM_7bj2ZOuUD8bsHtk"

[lint]
exclude_lints = ["screaming-snake-case-immutable", "screaming-snake-case-const"]
